Repository 2024-summer-project/AcademyManager_BE, pull requests merged in 2024-11, with the labels that each got.

#100 Fix/#83 bill
  prisma/schema.prisma
  src/app.js
  src/controllers/billController.js
  src/routes/billRouter.js
Labels: enhancement

#101 Feat/#36 api notice
  package-lock.json
  package.json
  prisma/schema.prisma
  public/notice/test_academy2/123/2/한글날.jpg
  src/app.js
  src/config/s3client.js
  src/controllers/noticeController.js
  src/controllers/userController.js
  src/lib/errors/errorCode.js
  src/lib/middlewares/handlingFile.js
  src/lib/middlewares/uploadImage.js
  src/routes/noticeRouter.js
  src/routes/userRouter.js
Labels: enhancement

#103 Fix/#102 decide registration
  src/controllers/registerationController.js
  src/routes/registerationRouter.js
Labels: enhancement

#107 Fix/#106 강사별로 강의 조회하도록 API 수정
  src/controllers/lectureController.js
  src/routes/lectureRouter.js
Labels: enhancement

#118 Feat/#87 chat
  package-lock.json
  package.json
  src/app.js
  src/controllers/chatController.js
  src/lib/chatDB/chatDB.js
  src/routes/chatRouter.js
  src/socket.js
Labels: enhancement

#114 Bug/#113 회원 기본 정보 수정 시, 생년월일 항목 추가
  src/controllers/userController.js
  src/routes/userRouter.js
Labels: bug

#119 Bug/#111 head count
  src/controllers/lectureController.js
  src/routes/lectureRouter.js
Labels: bug, enhancement

#122 Fix/#120 공지 API 전체적 수정
  src/controllers/noticeController.js
  src/routes/noticeRouter.js
Labels: enhancement

#125 Bug#124 default profile img
  src/controllers/userController.js
Labels: bug

#127 Fix/#121 bill fix
  prisma/schema.prisma
  src/controllers/billController.js
  src/routes/billRouter.js
Labels: bug, enhancement, wontfix

#129 Feat/#128 academy info api
  src/controllers/userController.js
  src/routes/userRouter.js
Labels: enhancement

#131 Feature/#117 quiz api
  src/app.js
  src/controllers/chatController.js
  src/controllers/quizController.js
  src/lib/chatDB/chatDB.js
  src/lib/mongo/mongo.js
  src/routes/quizRouter.js
  src/socket.js
Labels: enhancement

#134 Fix/#132 exam examtype list
  src/controllers/examTypeController.js
  src/controllers/lectureController.js
  src/routes/examTypeRouter.js
  src/routes/lectureRouter.js
Labels: enhancement

#135 Feat/#128 academy info api
  src/controllers/userController.js
  src/routes/userRouter.js
Labels: enhancement

#133 #130 feat: 비밀번호 확인(인증) API 구현
  src/controllers/userController.js
  src/routes/userRouter.js
Labels: enhancement

#139 Feat/#138 lecture parent
  package-lock.json
  package.json
  src/controllers/lectureController.js
  src/routes/lectureRouter.js
Labels: enhancement

#137 Bug/#136 exam metadata
  src/controllers/lectureController.js
  src/controllers/quizController.js
Labels: bug

#144 Bug/#104 class registration
  src/controllers/lectureController.js
  src/routes/lectureRouter.js
Labels: bug

#145 Feat/#143 get quiz info api
  src/controllers/quizController.js
  src/routes/quizRouter.js
Labels: enhancement
